name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
env:
  IMAGE_NAME: pavlozhuravlovob/my-app
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}

      - name: Update DigitalOcean App Platform Deployment
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          DOCKER_IMAGE: mayageo/my-private-repository:${{ steps.vars.outputs.sha_short }}
          APP_ID: ${{ secrets.DO_APP_ID }}
          SERVICE_NAME: lobster-app
        run: |
          # Fetch the current app spec
          app_spec=$(curl -X GET "https://api.digitalocean.com/v2/apps/$APP_ID" \
          -H "Authorization: Bearer $DO_API_TOKEN" \
          -H "Content-Type: application/json" | jq -r '.app.spec')
          
          # Update the Docker image in the app spec
          updated_app_spec=$(echo "$app_spec" | jq --arg image "$DOCKER_IMAGE" \
          '.services[] |= if .name == env.SERVICE_NAME then .image.repository = $image else . end')
  
          # Update the app with the new spec
          curl -X PUT "https://api.digitalocean.com/v2/apps/$APP_ID/spec" \
          -H "Authorization: Bearer $DO_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d "$updated_app_spec"

