name: Test

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: "Choose the build flavor"
        type: choice
        required: true
        default: "dev"
        options:
          - dev
          - stg
          - prod
          - emulator
          - monkey
      build_type:
        description: "Choose the build type"
        type: choice
        required: true
        default: "debug"
        options:
          - debug
          - release
      upload_to_firebase:
        description: "Upload build artifact to Firebase?"
        type: choice
        required: true
        default: "false"
        options:
          - true
          - false

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print selected values
        run: |
          echo "Selected branch: ${{ github.ref_name }}"
          echo "Selected flavor: ${{ github.event.inputs.flavor }}"
          echo "Selected build type: ${{ github.event.inputs.build_type }}"
          echo "Upload to Firebase: ${{ github.event.inputs.upload_to_firebase }}"